name: Build & Push Frontend (TechPanel)

on:
  push:
    branches: ["main"]
    paths:
      - "Dockerfile.prod"
      - ".github/workflows/docker-frontend.yml"
      - "src/**"
      - "public/**"
      - "package*.json"
      - "next.config.*"
      - "postcss.config.*"
      - "tailwind.config.*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.prod
          push: true
          tags: ghcr.io/devrafaelrabelo/techpanel-frontend:latest
