name: Docker Frontend
on:
  pull_request:
    branches: [develop, main]
    paths:
      - "apps/frontend/**"
      - ".github/workflows/docker-frontend.yml"

permissions:
  contents: read

concurrency:
  group: docker-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build sem push (seguro para PRs de forks). Ajuste o contexto/pasta se necessário.
      - name: Build Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./apps/frontend
          push: false
          tags: appgestaoti-frontend:pr-${{ github.event.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
